<?php

declare (strict_types=1);
/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Symfony\Bridge\Monolog\Command;

use Monolog\Formatter\Formatter_Interface;
use Monolog\Handler\Handler_Interface;
use Monolog\Level;
use Monolog\Log_Record;
use Symfony\Bridge\Monolog\Formatter\Console_Formatter;
use Symfony\Bridge\Monolog\Handler\Console_Handler;
use Symfony\Component\Console\Attribute\As_Command;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Exception\LogicException;
use Symfony\Component\Console\Exception\RuntimeException;
use Symfony\Component\Console\Input\Input_Interface;
use Symfony\Component\Console\Input\Input_Option;
use Symfony\Component\Console\Output\Output_Interface;
use Symfony\Component\Expression_Language\Expression_Language;
/**
 * @author Grégoire Pineau <lyrixx@lyrixx.info>
 */
#[As_Command(name: 'server:log', description: 'Start a log server that displays logs in real time')]
class Server_Log_Command extends Command
{
    private const BG_COLOR = ['black', 'blue', 'cyan', 'green', 'magenta', 'red', 'white', 'yellow'];
    private Expression_Language $el;
    private Handler_Interface $handler;
    public function is_enabled(): bool
    {
        if (!class_exists(Console_Formatter::class)) {
            return false;
        }
        // based on a symfony/symfony package, it crashes due a missing FormatterInterface from monolog/monolog
        if (!interface_exists(Formatter_Interface::class)) {
            return false;
        }
        return parent::is_enabled();
    }
    protected function configure(): void
    {
        if (!class_exists(Console_Formatter::class)) {
            return;
        }
        $this->add_option('host', null, Input_Option::VALUE_REQUIRED, 'The server host', '0.0.0.0:9911')->add_option('format', null, Input_Option::VALUE_REQUIRED, 'The line format', Console_Formatter::SIMPLE_FORMAT)->add_option('date-format', null, Input_Option::VALUE_REQUIRED, 'The date format', Console_Formatter::SIMPLE_DATE)->add_option('filter', null, Input_Option::VALUE_REQUIRED, 'An expression to filter log. Example: "level > 200 or channel in [\'app\', \'doctrine\']"')->set_help(<<<'EOF'
        <info>%command.name%</info> starts a log server to display in real time the log
        messages generated by your application:
        
          <info>php %command.full_name%</info>
        
        To filter the log messages using any ExpressionLanguage compatible expression, use the <info>--filter</> option:
        
        <info>php %command.full_name% --filter="level > 200 or channel in ['app', 'doctrine']"</info>
        EOF);
    }
    protected function execute(Input_Interface $input, Output_Interface $output): int
    {
        $filter = $input->get_option('filter');
        if ($filter) {
            if (!class_exists(Expression_Language::class)) {
                throw new LogicException('Package "symfony/expression-language" is required to use the "filter" option. Try running "composer require symfony/expression-language".');
            }
            $this->el = new Expression_Language();
        }
        $this->handler = new Console_Handler($output, true, [Output_Interface::VERBOSITY_NORMAL => Level::Debug]);
        $this->handler->set_formatter(new Console_Formatter(['format' => str_replace('\n', "\n", $input->get_option('format')), 'date_format' => $input->get_option('date-format'), 'colors' => $output->is_decorated(), 'multiline' => Output_Interface::VERBOSITY_DEBUG <= $output->get_verbosity()]));
        if (!str_contains((string) $host = $input->get_option('host'), '://')) {
            $host = 'tcp://' . $host;
        }
        if (!$socket = stream_socket_server($host, $errno, $errstr)) {
            throw new RuntimeException(\sprintf('Server start failed on "%s": ', $host) . $errstr . ' ' . $errno);
        }
        foreach ($this->get_logs($socket) as $client_id => $message) {
            $record = unserialize(base64_decode((string) $message));
            // Impossible to decode the message, give up.
            if (false === $record) {
                continue;
            }
            if ($filter && !$this->el->evaluate($filter, $record)) {
                continue;
            }
            $this->display_log($output, $client_id, $record);
        }
        return 0;
    }
    private function get_logs($socket): iterable
    {
        $sockets = [(int) $socket => $socket];
        $write = [];
        while (true) {
            $read = $sockets;
            stream_select($read, $write, $write, null);
            foreach ($read as $stream) {
                if ($socket === $stream) {
                    $stream = stream_socket_accept($socket);
                    $sockets[(int) $stream] = $stream;
                } elseif (feof($stream)) {
                    unset($sockets[(int) $stream]);
                    fclose($stream);
                } else {
                    yield (int) $stream => fgets($stream);
                }
            }
        }
    }
    private function display_log(Output_Interface $output, int $client_id, array $record): void
    {
        if (isset($record['log_id'])) {
            $client_id = unpack('H*', $record['log_id'])[1];
        }
        $log_block = \sprintf('<bg=%s> </>', self::BG_COLOR[$client_id % 8]);
        $output->write($log_block);
        $record = new Log_Record(
            $record['datetime'],
            $record['channel'],
            Level::from_value($record['level']),
            $record['message'],
            // We wrap context and extra, because they have been already dumped.
            // So they are instance of Symfony\Component\VarDumper\Cloner\Data
            // But LogRecord expects array
            ['data' => $record['context']],
            ['data' => $record['extra']]
        );
        $this->handler->handle($record);
    }
}