<?php

declare(strict_types=1);

use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\DependencyInjection\Exception\LogicException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class ProjectServiceContainer extends Container
{
    protected $parameters = [];

    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMap = [
            'Bar\\Foo' => 'getFooService',
            'Foo\\Foo' => 'getFoo2Service',
        ];

        $this->aliases = [];
    }

    public function compile(): void
    {
        throw new LogicException('You cannot compile a dumped container that was already compiled.');
    }

    public function isCompiled(): bool
    {
        return true;
    }

    /**
     * Gets the public 'Bar\Foo' shared service.
     *
     * @return \Bar\Foo
     */
    protected static function getFooService($container)
    {
        return $container->services['Bar\\Foo'] = new \Bar\Foo();
    }

    /**
     * Gets the public 'Foo\Foo' shared service.
     *
     * @return \Foo\Foo
     */
    protected static function getFoo2Service($container)
    {
        return $container->services['Foo\\Foo'] = new \Foo\Foo();
    }
}
