<?php

declare (strict_types=1);
/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Symfony\Component\Dotenv\Command;

use Symfony\Component\Console\Attribute\As_Command;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\Input_Argument;
use Symfony\Component\Console\Input\Input_Interface;
use Symfony\Component\Console\Input\Input_Option;
use Symfony\Component\Console\Output\Output_Interface;
use Symfony\Component\Dependency_Injection\Attribute\Autoconfigure;
use Symfony\Component\Dotenv\Dotenv;
/**
 * A console command to compile .env files into a PHP-optimized file called .env.local.php.
 *
 * To use this command, first register it explicitly as a service, e.g in your services.yaml file:
 *
 *     ```yaml
 *     services:
 *         # [...]
 *         Symfony\Component\Dotenv\Command\DotenvDumpCommand: ~
 *     ```
 */
#[Autoconfigure(bind: ['$projectDir' => '%kernel.project_dir%', '$defaultEnv' => '%kernel.environment%'])]
#[As_Command(name: 'dotenv:dump', description: 'Compile .env files to .env.local.php')]
final class Dotenv_Dump_Command extends Command
{
    public function __construct(private readonly string $project_dir, private readonly ?string $default_env = null)
    {
        parent::__construct();
    }
    protected function configure(): void
    {
        $this->set_definition([new Input_Argument('env', null === $this->default_env ? Input_Argument::REQUIRED : Input_Argument::OPTIONAL, 'The application environment to dump .env files for - e.g. "prod".')])->add_option('empty', null, Input_Option::VALUE_NONE, 'Ignore the content of .env files')->set_help(<<<'EOT'
        The <info>%command.name%</info> command compiles .env files into a PHP-optimized file called .env.local.php.
        
            <info>%command.full_name%</info>
        EOT);
    }
    protected function execute(Input_Interface $input, Output_Interface $output): int
    {
        $config = [];
        $dotenv_path = $this->get_dotenv_path($config);
        $env = $input->get_argument('env') ?? $this->default_env;
        $env_key = $config['env_var_name'] ?? 'APP_ENV';
        if ($input->get_option('empty')) {
            $vars = [$env_key => $env];
        } else {
            $vars = $this->load_env($dotenv_path, $env, $config);
            $env = $vars[$env_key];
        }
        $vars = var_export($vars, true);
        $vars = <<<EOF
        <?php
        
        // This file was generated by running "php bin/console dotenv:dump {$env}"
        
        return {$vars};
        
        EOF;
        file_put_contents($dotenv_path . '.local.php', $vars, \LOCK_EX);
        $output->writeln(\sprintf('Successfully dumped %s files in <info>%1$s.local.php</> for the <info>%s</> environment.', basename($dotenv_path), $env));
        return 0;
    }
    private function get_dotenv_path(array &$config): string
    {
        $config = [];
        $project_dir = $this->project_dir;
        if (is_file($project_dir)) {
            $config = ['dotenv_path' => basename($project_dir)];
            $project_dir = \dirname($project_dir);
        }
        $composer_file = $project_dir . '/composer.json';
        $config += $_SERVER['APP_RUNTIME_OPTIONS'] ?? (is_file($composer_file) ? json_decode(file_get_contents($composer_file), true) : [])['extra']['runtime'] ?? [];
        return $project_dir . '/' . ($config['dotenv_path'] ?? '.env');
    }
    private function load_env(string $dotenv_path, string $env, array $config): array
    {
        $env_key = $config['env_var_name'] ?? 'APP_ENV';
        $test_envs = $config['test_envs'] ?? ['test'];
        $dotenv = new Dotenv($env_key);
        $globals_backup = [$_SERVER, $_ENV];
        unset($_SERVER[$env_key]);
        $_ENV = [$env_key => $env];
        $_SERVER['SYMFONY_DOTENV_VARS'] = implode(',', array_keys($_SERVER));
        try {
            $dotenv->load_env($dotenv_path, null, 'dev', $test_envs);
            unset($_ENV['SYMFONY_DOTENV_VARS']);
            unset($_ENV['SYMFONY_DOTENV_PATH']);
            return $_ENV;
        } finally {
            [$_SERVER, $_ENV] = $globals_backup;
        }
    }
}