<?php

declare (strict_types=1);
/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Symfony\Bridge\Doctrine\Cache_Warmer;

use Doctrine\Persistence\Manager_Registry;
use Symfony\Component\Http_Kernel\Cache_Warmer\Cache_Warmer_Interface;
/**
 * The proxy generator cache warmer generates all entity proxies.
 *
 * In the process of generating proxies the cache for all the metadata is primed also,
 * since this information is necessary to build the proxies in the first place.
 *
 * @author Benjamin Eberlei <kontakt@beberlei.de>
 */
final readonly class Proxy_Cache_Warmer implements Cache_Warmer_Interface
{
    public function __construct(private Manager_Registry $registry)
    {
    }
    /**
     * This cache warmer is not optional, without proxies fatal error occurs!
     */
    public function is_optional(): bool
    {
        return false;
    }
    public function warm_up(string $cache_dir, ?string $build_dir = null): array
    {
        $files = [];
        foreach ($this->registry->get_managers() as $em) {
            // we need the directory no matter the proxy cache generation strategy
            if (!is_dir($proxy_cache_dir = $em->get_configuration()->get_proxy_dir())) {
                if (false === @mkdir($proxy_cache_dir, 0777, true) && !is_dir($proxy_cache_dir)) {
                    throw new \RuntimeException(\sprintf('Unable to create the Doctrine Proxy directory "%s".', $proxy_cache_dir));
                }
            } elseif (!is_writable($proxy_cache_dir)) {
                throw new \RuntimeException(\sprintf('The Doctrine Proxy directory "%s" is not writeable for the current system user.', $proxy_cache_dir));
            }
            // if proxies are autogenerated we don't need to generate them in the cache warmer
            if ($em->get_configuration()->get_auto_generate_proxy_classes()) {
                continue;
            }
            $classes = $em->get_metadata_factory()->get_all_metadata();
            $em->get_proxy_factory()->generate_proxy_classes($classes);
            foreach (scandir($proxy_cache_dir) as $file) {
                if (!is_dir($file = $proxy_cache_dir . '/' . $file)) {
                    $files[] = $file;
                }
            }
        }
        return $files;
    }
}